/**
 * Generated by Sanity TypeGen (placeholder).
 *
 * This file is a hand-written stand-in for the output of
 * `npx sanity schema extract && npx sanity typegen generate`.
 * It follows the same naming and shape conventions so that
 * regenerating against a real project transparently replaces it.
 */

export type Slug = {
  _type: "slug";
  current: string | null;
};

export type ReferenceTo = {
  _type: "reference";
  _ref: string;
  _weak?: boolean;
  _strengthenOnPublish?: boolean;
};

export type ImageWithHotspot = {
  _type: "image";
  asset: ReferenceTo;
  hotspot?: {
    x: number;
    y: number;
    height: number;
    width: number;
  };
  crop?: {
    top: number;
    bottom: number;
    left: number;
    right: number;
  };
};

export type PortableTextBlock = {
  _type: "block";
  _key?: string;
  style?: string;
  listItem?: string;
  level?: number;
  children?: Array<{
    _key?: string;
    _type: string;
    marks?: string[];
    text?: string;
  }>;
  markDefs?: Array<{
    _key?: string;
    _type: string;
    href?: string;
  }>;
};

export type SanityDocument = {
  _id: string;
  _type: string;
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
};

export type Product = SanityDocument & {
  _type: "product";
  title?: string;
  slug?: Slug;
  price?: number;
  originalPrice?: number;
  condition?: "New" | "Used" | "Refurbished";
  category?: ReferenceTo;
  mainImage?: ImageWithHotspot;
  gallery?: Array<ImageWithHotspot>;
  description?: Array<PortableTextBlock>;
  isFeatured?: boolean;
  inStock?: boolean;
};

export type Category = SanityDocument & {
  _type: "category";
  title?: string;
  slug?: Slug;
  image?: ImageWithHotspot;
  description?: string;
};

export type Banner = SanityDocument & {
  _type: "banner";
  title?: string;
  subtitle?: string;
  offerTag?: string;
  image?: ImageWithHotspot;
  buttonText?: string;
  link?: string;
  isActive?: boolean;
  sortOrder?: number;
};

export type SiteSettings = SanityDocument & {
  _type: "siteSettings";
  shopName?: string;
  phone?: string;
  whatsapp?: string;
  address?: string;
  facebook?: string;
};

type ProductProjection = {
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: Slug | null;
  price: number | null;
  originalPrice: number | null;
  condition: "New" | "Used" | "Refurbished" | null;
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  mainImage: ImageWithHotspot | null;
  gallery: Array<ImageWithHotspot> | null;
  description: Array<PortableTextBlock> | null;
  isFeatured: boolean | null;
  inStock: boolean | null;
};

export type GetAllProductsQueryResult = Array<ProductProjection>;

export type GetFeaturedProductsQueryResult = Array<ProductProjection>;

export type GetProductsByCategoryQueryResult = Array<ProductProjection>;

export type GetSingleProductQueryResult = ProductProjection | null;

export type GetCategoriesQueryResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: Slug | null;
  image: ImageWithHotspot | null;
  description: string | null;
}>;

export type GetHeroBannersQueryResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  subtitle: string | null;
  offerTag: string | null;
  image: ImageWithHotspot | null;
  buttonText: string | null;
  link: string | null;
  isActive: boolean | null;
  sortOrder: number | null;
}>;

export type GetSiteSettingsQueryResult = {
  shopName: string | null;
  phone: string | null;
  whatsapp: string | null;
  address: string | null;
  facebook: string | null;
} | null;
