/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  shopName?: string;
  phone?: string;
  whatsapp?: string;
  address?: string;
  facebook?: string;
};

export type Banner = {
  _id: string;
  _type: "banner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subtitle?: string;
  offerTag?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  buttonText?: string;
  link?: string;
  isActive?: boolean;
  sortOrder?: number;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  price?: number;
  originalPrice?: number;
  condition?: "New" | "Used" | "Refurbished";
  category?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "category";
  };
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  isFeatured?: boolean;
  inStock?: boolean;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = SiteSettings | Banner | Product | Category | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./lib/sanity.queries.ts
// Variable: getAllProductsQuery
// Query: *[_type == "product"] | order(_createdAt desc) {    _id,    _createdAt,    title,    slug,    price,    originalPrice,    condition,    category->{ _id, title, slug },    mainImage,    gallery,    description,    isFeatured,    inStock  }
export type GetAllProductsQueryResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: Slug | null;
  price: number | null;
  originalPrice: number | null;
  condition: "New" | "Refurbished" | "Used" | null;
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  gallery: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  isFeatured: boolean | null;
  inStock: boolean | null;
}>;
// Variable: getFeaturedProductsQuery
// Query: *[_type == "product" && isFeatured == true] | order(_createdAt desc) {    _id,    _createdAt,    title,    slug,    price,    originalPrice,    condition,    category->{ _id, title, slug },    mainImage,    gallery,    description,    isFeatured,    inStock  }
export type GetFeaturedProductsQueryResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: Slug | null;
  price: number | null;
  originalPrice: number | null;
  condition: "New" | "Refurbished" | "Used" | null;
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  gallery: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  isFeatured: true;
  inStock: boolean | null;
}>;
// Variable: getProductsByCategoryQuery
// Query: *[_type == "product" && category->slug.current == $slug] | order(_createdAt desc) {    _id,    _createdAt,    title,    slug,    price,    originalPrice,    condition,    category->{ _id, title, slug },    mainImage,    gallery,    description,    isFeatured,    inStock  }
export type GetProductsByCategoryQueryResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: Slug | null;
  price: number | null;
  originalPrice: number | null;
  condition: "New" | "Refurbished" | "Used" | null;
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  gallery: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  isFeatured: boolean | null;
  inStock: boolean | null;
}>;
// Variable: getSingleProductQuery
// Query: *[_type == "product" && slug.current == $slug][0] {    _id,    _createdAt,    title,    slug,    price,    originalPrice,    condition,    category->{ _id, title, slug },    mainImage,    gallery,    description,    isFeatured,    inStock  }
export type GetSingleProductQueryResult = {
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: Slug | null;
  price: number | null;
  originalPrice: number | null;
  condition: "New" | "Refurbished" | "Used" | null;
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  gallery: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  isFeatured: boolean | null;
  inStock: boolean | null;
} | null;
// Variable: getCategoriesQuery
// Query: *[_type == "category"] | order(title asc) {    _id,    _createdAt,    title,    slug,    image,    description  }
export type GetCategoriesQueryResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: Slug | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: string | null;
}>;
// Variable: getHeroBannersQuery
// Query: *[_type == "banner" && isActive == true] | order(sortOrder asc) {    _id,    _createdAt,    title,    subtitle,    offerTag,    image,    buttonText,    link,    isActive,    sortOrder  }
export type GetHeroBannersQueryResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  subtitle: string | null;
  offerTag: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  buttonText: string | null;
  link: string | null;
  isActive: true;
  sortOrder: number | null;
}>;
// Variable: getSiteSettingsQuery
// Query: *[_type == "siteSettings"][0] {    shopName,    phone,    whatsapp,    address,    facebook  }
export type GetSiteSettingsQueryResult = {
  shopName: string | null;
  phone: string | null;
  whatsapp: string | null;
  address: string | null;
  facebook: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"product\"] | order(_createdAt desc) {\n    _id,\n    _createdAt,\n    title,\n    slug,\n    price,\n    originalPrice,\n    condition,\n    category->{ _id, title, slug },\n    mainImage,\n    gallery,\n    description,\n    isFeatured,\n    inStock\n  }\n": GetAllProductsQueryResult;
    "\n  *[_type == \"product\" && isFeatured == true] | order(_createdAt desc) {\n    _id,\n    _createdAt,\n    title,\n    slug,\n    price,\n    originalPrice,\n    condition,\n    category->{ _id, title, slug },\n    mainImage,\n    gallery,\n    description,\n    isFeatured,\n    inStock\n  }\n": GetFeaturedProductsQueryResult;
    "\n  *[_type == \"product\" && category->slug.current == $slug] | order(_createdAt desc) {\n    _id,\n    _createdAt,\n    title,\n    slug,\n    price,\n    originalPrice,\n    condition,\n    category->{ _id, title, slug },\n    mainImage,\n    gallery,\n    description,\n    isFeatured,\n    inStock\n  }\n": GetProductsByCategoryQueryResult;
    "\n  *[_type == \"product\" && slug.current == $slug][0] {\n    _id,\n    _createdAt,\n    title,\n    slug,\n    price,\n    originalPrice,\n    condition,\n    category->{ _id, title, slug },\n    mainImage,\n    gallery,\n    description,\n    isFeatured,\n    inStock\n  }\n": GetSingleProductQueryResult;
    "\n  *[_type == \"category\"] | order(title asc) {\n    _id,\n    _createdAt,\n    title,\n    slug,\n    image,\n    description\n  }\n": GetCategoriesQueryResult;
    "\n  *[_type == \"banner\" && isActive == true] | order(sortOrder asc) {\n    _id,\n    _createdAt,\n    title,\n    subtitle,\n    offerTag,\n    image,\n    buttonText,\n    link,\n    isActive,\n    sortOrder\n  }\n": GetHeroBannersQueryResult;
    "\n  *[_type == \"siteSettings\"][0] {\n    shopName,\n    phone,\n    whatsapp,\n    address,\n    facebook\n  }\n": GetSiteSettingsQueryResult;
  }
}
